spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HomestayBooking
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8081

jwt:
  secretKey: QWERTYUIOPasdfghJKLzxcvbnm1234567890QWERTYUIOPasdfgh
  accessTokenExpiration: 15
  refreshTokenExpiration: 7